# Generated by Django 2.0.8 on 2018-11-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('addressComplement', models.CharField(max_length=40)),
                ('cep', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=14)),
            ],
        ),
    ]
