# Generated by Django 2.0.8 on 2018-11-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='parcial_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tickets',
            field=models.ManyToManyField(help_text='Tickets do Carrinho', null=True, to='ticket.Ticket', verbose_name='Ticket'),
        ),
    ]
