# Generated by Django 2.0.8 on 2018-11-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomboniere', '0006_auto_20181120_1326'),
        ('ticket', '0002_auto_20181119_2314'),
        ('cart', '0002_auto_20181120_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tickets',
        ),
        migrations.CreateModel(
            name='ItemCombos',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.Item')),
                ('combos', models.ManyToManyField(help_text='Combos do Carrinho', null=True, to='bomboniere.Combo', verbose_name='Combos')),
            ],
            bases=('cart.item',),
        ),
        migrations.CreateModel(
            name='ItemProducts',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.Item')),
                ('products', models.ManyToManyField(help_text='Produtos do Carrinho', null=True, to='bomboniere.Product', verbose_name='Produtos')),
            ],
            bases=('cart.item',),
        ),
        migrations.CreateModel(
            name='ItemTickets',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.Item')),
                ('tickets', models.ManyToManyField(help_text='Tickets do Carrinho', null=True, to='ticket.Ticket', verbose_name='Tickets')),
            ],
            bases=('cart.item',),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_combos',
            field=models.ManyToManyField(help_text='Combos do Carrinho', null=True, to='cart.ItemCombos', verbose_name='Combos'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_products',
            field=models.ManyToManyField(help_text='Produtos do Carrinho', null=True, to='cart.ItemProducts', verbose_name='Produtos'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_tickets',
            field=models.ManyToManyField(help_text='Tickets do Carrinho', null=True, to='cart.ItemTickets', verbose_name='Ticket'),
        ),
    ]
