# Generated by Django 2.0.8 on 2018-11-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20181121_2349'),
        ('bomboniere', '0006_auto_20181120_1326'),
        ('cart', '0003_auto_20181121_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcombos',
            name='combos',
        ),
        migrations.RemoveField(
            model_name='itemcombos',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='itemproducts',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='itemproducts',
            name='products',
        ),
        migrations.RemoveField(
            model_name='itemtickets',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='itemtickets',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_combos',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_tickets',
        ),
        migrations.AddField(
            model_name='cart',
            name='combos',
            field=models.ManyToManyField(help_text='Combos do Carrinho', to='bomboniere.Combo', verbose_name='Combos'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(help_text='Produtos do Carrinho', to='bomboniere.Product', verbose_name='Produtos'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tickets',
            field=models.ManyToManyField(help_text='Tickets do Carrinho', to='ticket.Ticket', verbose_name='Ticket'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemCombos',
        ),
        migrations.DeleteModel(
            name='ItemProducts',
        ),
        migrations.DeleteModel(
            name='ItemTickets',
        ),
    ]
