# Generated by Django 2.0.8 on 2018-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20181121_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='parcial_price',
            field=models.FloatField(default=0, help_text='Preço Parcial da Compra', verbose_name='Preço Parcial da Compra'),
        ),
    ]
