# Generated by Django 2.0.8 on 2018-11-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20181122_0246'),
        ('cart', '0005_auto_20181122_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seats',
            field=models.ManyToManyField(help_text='Assentos', to='room.Seat', verbose_name='Assento'),
        ),
    ]
