# Generated by Django 2.0.8 on 2018-11-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seats',
        ),
    ]
