# Generated by Django 2.0.8 on 2018-11-22 01:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da Sala', max_length=10, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(help_text='Fileira do Assento', max_length=1, verbose_name='Fileira')),
                ('number', models.IntegerField(default=0, help_text='Número do Assento', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', related_query_name='seats', to='room.Room')),
            ],
            options={
                'verbose_name': 'Assento',
                'verbose_name_plural': 'Assentos',
            },
        ),
    ]
