# Generated by Django 2.0.8 on 2018-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['row'], 'verbose_name': 'Assento', 'verbose_name_plural': 'Assentos'},
        ),
        migrations.AddField(
            model_name='room',
            name='spare',
            field=models.BooleanField(default=True, help_text='Assento Livre', verbose_name='Livre'),
        ),
        migrations.AddField(
            model_name='seat',
            name='spare',
            field=models.BooleanField(default=True, help_text='Assento Livre', verbose_name='Livre'),
        ),
    ]
