# Generated by Django 2.0.8 on 2018-11-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Boleto Bancário', 'Boleto Bancário'), ('NA', 'N/A')], default='NA', help_text='Tipo de Pagamento', max_length=20, verbose_name='Tipo de Pagamento')),
                ('ownerName', models.CharField(default='', help_text='Nome do pagador do boleto', max_length=255, verbose_name='Pagador do boleto')),
                ('ownerCpf', models.BigIntegerField(default=0, help_text='CPF do pagador do boleto', verbose_name='CPF do pagador')),
                ('expirationDate', models.DateField(help_text='Data de vencimento do boleto', verbose_name='Data de vencimento')),
            ],
            options={
                'verbose_name': 'Boleto Bancário',
                'verbose_name_plural': 'Boletos Bancários',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Boleto Bancário', 'Boleto Bancário'), ('NA', 'N/A')], default='NA', help_text='Tipo de Pagamento', max_length=20, verbose_name='Tipo de Pagamento')),
                ('_ownerName', models.CharField(default='', help_text='Nome do pagador do boleto', max_length=255, verbose_name='Pagador do boleto')),
                ('_cardNumber', models.CharField(default='', help_text='Número do cartão de crédito', max_length=16, verbose_name='Número do cartão')),
                ('_securityCode', models.IntegerField(default=0, help_text='Código de segurança do cartão de crédito', verbose_name='Código de segurança')),
                ('_expireMonth', models.IntegerField(default=0, help_text='Mês de vencimento do cartão de crédito', verbose_name='Mês de vencimento')),
                ('_expireYear', models.IntegerField(default=0, help_text='Ano de vencimento do cartão de crédito', verbose_name='Ano de vencimento')),
                ('_installmentNumber', models.IntegerField(default=1, help_text='Quantidade de parcelas do pagamento', verbose_name='Parcelas')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Purchase'),
        ),
        migrations.AddField(
            model_name='bankticket',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Purchase'),
        ),
    ]
