# Generated by Django 2.0.8 on 2018-11-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0003_auto_20181123_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusPayment', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Aguardando', help_text='Status do Pagamento', max_length=20, verbose_name='Status')),
                ('_ownerName', models.CharField(default='', help_text='Nome do pagador do boleto', max_length=255, verbose_name='Pagador do boleto')),
                ('_ownerCpf', models.BigIntegerField(default=0, help_text='CPF do pagador do boleto', verbose_name='CPF do pagador')),
                ('_expirationDate', models.DateField(help_text='Data de vencimento do boleto', verbose_name='Data de vencimento')),
                ('_payment_type', models.CharField(default='Boleto Bancário', editable=False, help_text='Tipo de Pagamento', max_length=20, verbose_name='Tipo de Pagamento')),
                ('_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.Purchase')),
            ],
            options={
                'verbose_name': 'Boleto Bancário',
                'verbose_name_plural': 'Boletos Bancários',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusPayment', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Aguardando', help_text='Status do Pagamento', max_length=20, verbose_name='Status')),
                ('_ownerName', models.CharField(default='', help_text='Nome do dono do cartão', max_length=255, verbose_name='Nome no cartão')),
                ('_cardNumber', models.CharField(default='', help_text='Número do cartão de crédito', max_length=16, verbose_name='Número do cartão')),
                ('_securityCode', models.IntegerField(default=0, help_text='Código de segurança do cartão de crédito', verbose_name='Código de segurança')),
                ('_expireMonth', models.IntegerField(default=0, help_text='Mês de vencimento do cartão de crédito', verbose_name='Mês de vencimento')),
                ('_expireYear', models.IntegerField(default=0, help_text='Ano de vencimento do cartão de crédito', verbose_name='Ano de vencimento')),
                ('_installmentNumber', models.IntegerField(default=1, help_text='Quantidade de parcelas do pagamento', verbose_name='Parcelas')),
                ('_payment_type', models.CharField(default='Cartão de Crédito', editable=False, help_text='Tipo de Pagamento', max_length=20, verbose_name='Tipo de Pagamento')),
                ('_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.Purchase')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
    ]
