# Generated by Django 2.0.8 on 2018-11-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='_ownerName',
            field=models.CharField(default='', help_text='Nome do dono do cartão', max_length=255, verbose_name='Nome no cartão'),
        ),
    ]
