# Generated by Django 2.0.8 on 2018-11-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20181123_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankticket',
            old_name='expirationDate',
            new_name='_expirationDate',
        ),
        migrations.RenameField(
            model_name='bankticket',
            old_name='ownerCpf',
            new_name='_ownerCpf',
        ),
        migrations.RenameField(
            model_name='bankticket',
            old_name='ownerName',
            new_name='_ownerName',
        ),
        migrations.RenameField(
            model_name='bankticket',
            old_name='purchase',
            new_name='_purchase',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='purchase',
            new_name='_purchase',
        ),
        migrations.RemoveField(
            model_name='bankticket',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='bankticket',
            name='_payment_type',
            field=models.CharField(default='Boleto Bancário', editable=False, help_text='Tipo de Pagamento', max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AddField(
            model_name='bankticket',
            name='statusPayment',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Aguardando', help_text='Status do Pagamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='_payment_type',
            field=models.CharField(default='Cartão de Crédito', editable=False, help_text='Tipo de Pagamento', max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='statusPayment',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Aguardando', help_text='Status do Pagamento', max_length=20, verbose_name='Status'),
        ),
    ]
