# Generated by Django 2.0.8 on 2018-11-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Nome da Espetáculo', max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo')),
                ('poster', models.ImageField(blank=True, help_text='Poster do Espetáculo', max_length=500, null=True, upload_to='media/', verbose_name='Poster')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração')),
                ('classification', models.CharField(choices=[('LIVRE', 'Livre'), ('10ANOS', '10 Anos'), ('12ANOS', '12 Anos'), ('14ANOS', '14 Anos'), ('16ANOS', '16 Anos'), ('MAIORES18', 'Maiores de 18 Anos')], default='LIVRE', help_text='Classificação Indicativa do Espetáculo', max_length=20, verbose_name='Classificação Indicativa')),
                ('spectacle_type', models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo')),
                ('synopsis', models.TextField(default='', help_text='Sinopse do Filme', max_length=500, verbose_name='Sinopse')),
                ('diretor', models.CharField(default='', help_text='Diretor do Filme', max_length=255, verbose_name='Diretor')),
                ('cast', models.TextField(default='', help_text='Elenco participante do Filme', max_length=500, verbose_name='Elenco')),
                ('producer', models.CharField(default='', help_text='Produtor do Filme', max_length=255, verbose_name='Produtor')),
                ('writer', models.CharField(default='', help_text='Escritor do Filme', max_length=255, verbose_name='Escritor')),
                ('gender', models.CharField(choices=[('ANIMACAO', 'Animação'), ('ACAO', 'Ação'), ('BIOGRAFIA', 'Biografia'), ('COMEDIA', 'Comédia'), ('DOCUMENTARIO', 'Documentário'), ('DRAMA', 'Drama'), ('FICCAO', 'Ficção Científica'), ('MUSICAL', 'Musical'), ('NA', 'N/A'), ('ROMANCE', 'Romance'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror')], default='NA', help_text='Genêro do Filme', max_length=20, verbose_name='Genêro')),
                ('trailer', models.CharField(default='', help_text='Link do Trailer do Filme', max_length=255, verbose_name='Trailer')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Nome da Espetáculo', max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo')),
                ('poster', models.ImageField(blank=True, help_text='Poster do Espetáculo', max_length=500, null=True, upload_to='media/', verbose_name='Poster')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração')),
                ('classification', models.CharField(choices=[('LIVRE', 'Livre'), ('10ANOS', '10 Anos'), ('12ANOS', '12 Anos'), ('14ANOS', '14 Anos'), ('16ANOS', '16 Anos'), ('MAIORES18', 'Maiores de 18 Anos')], default='LIVRE', help_text='Classificação Indicativa do Espetáculo', max_length=20, verbose_name='Classificação Indicativa')),
                ('spectacle_type', models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo')),
                ('synopsis', models.TextField(default='', help_text='Sinopse do Peça', max_length=500, verbose_name='Sinopse')),
                ('diretor', models.CharField(default='', help_text='Diretor do Peça', max_length=255, verbose_name='Diretor')),
                ('cast', models.TextField(default='', help_text='Elenco participante do Peça', max_length=500, verbose_name='Elenco')),
                ('writer', models.CharField(default='', help_text='Escritor do Peça', max_length=255, verbose_name='Escritor')),
                ('producer', models.CharField(default='', help_text='Produtor do Peça', max_length=255, verbose_name='Produtor')),
                ('gender', models.CharField(choices=[('AUTO', 'Auto'), ('BURLESCO', 'Burlesco'), ('CIRCENSE', 'Circense'), ('COMEDIA', 'Comédia'), ('DRAMA', 'Drama'), ('FARSA', 'Farsa'), ('MIMICA', 'Mímica'), ('MUSAICAL', 'Musical'), ('OUTROS', 'Outros'), ('TRAGEDIA', 'Tragédia'), ('TRAGICOMEDIA', 'Tragicomédia')], default='OUTROS', help_text='Genêro do Peça', max_length=15, verbose_name='Genêro')),
            ],
            options={
                'verbose_name': 'Peça Teatral',
                'verbose_name_plural': 'Peças Teatrais',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Nome da Espetáculo', max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo')),
                ('poster', models.ImageField(blank=True, help_text='Poster do Espetáculo', max_length=500, null=True, upload_to='media/', verbose_name='Poster')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração')),
                ('classification', models.CharField(choices=[('LIVRE', 'Livre'), ('10ANOS', '10 Anos'), ('12ANOS', '12 Anos'), ('14ANOS', '14 Anos'), ('16ANOS', '16 Anos'), ('MAIORES18', 'Maiores de 18 Anos')], default='LIVRE', help_text='Classificação Indicativa do Espetáculo', max_length=20, verbose_name='Classificação Indicativa')),
                ('spectacle_type', models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo')),
                ('band', models.CharField(default='', help_text='Nome da(o) Banda/Artista', max_length=255, verbose_name='Banda/Artista')),
                ('tour', models.CharField(default='', help_text='Nome da Turnê', max_length=255, verbose_name='Turnê')),
                ('description', models.TextField(default='', help_text='Descrição do Show', max_length=500, verbose_name='Descrição do Show')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
            },
        ),
        migrations.CreateModel(
            name='Spectacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Nome da Espetáculo', max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo')),
                ('poster', models.ImageField(blank=True, help_text='Poster do Espetáculo', max_length=500, null=True, upload_to='media/', verbose_name='Poster')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração')),
                ('classification', models.CharField(choices=[('LIVRE', 'Livre'), ('10ANOS', '10 Anos'), ('12ANOS', '12 Anos'), ('14ANOS', '14 Anos'), ('16ANOS', '16 Anos'), ('MAIORES18', 'Maiores de 18 Anos')], default='LIVRE', help_text='Classificação Indicativa do Espetáculo', max_length=20, verbose_name='Classificação Indicativa')),
                ('spectacle_type', models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo')),
            ],
            options={
                'verbose_name': 'Espetáculo',
                'verbose_name_plural': 'Espetáculos',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='spectacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spectacle.Spectacle'),
        ),
        migrations.AddField(
            model_name='play',
            name='spectacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spectacle.Spectacle'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spectacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spectacle.Spectacle'),
        ),
    ]
