# Generated by Django 2.0.8 on 2018-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectacle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo'),
        ),
        migrations.AddField(
            model_name='play',
            name='type',
            field=models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo'),
        ),
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo'),
        ),
        migrations.AddField(
            model_name='spectacle',
            name='type',
            field=models.CharField(choices=[('FILME', 'Filme'), ('SHOW', 'Show'), ('PECA', 'Peça Teatral'), ('NA', 'N/A')], default='NA', help_text='Tipo do Espetáculo', max_length=15, verbose_name='Tipo do Espetáculo'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo'),
        ),
        migrations.AlterField(
            model_name='play',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='play',
            name='status',
            field=models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo'),
        ),
        migrations.AlterField(
            model_name='show',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duração do Espetáculo em minutos', verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='status',
            field=models.CharField(choices=[('PREESTREIA', 'Pré-Estréia'), ('EMCARTAZ', 'Em Cartaz'), ('LANCAMENTO', 'Lançamento'), ('FORACARTAZ', 'Fora de Cartaz'), ('EMBREVE', 'Em Breve')], default='EMBREVE', help_text='Status do Espetáculo', max_length=15, verbose_name='Status do Espetáculo'),
        ),
    ]
