# Generated by Django 2.0.8 on 2018-11-13 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do Produto', max_length=50, verbose_name='Nome')),
                ('description', models.TextField(default='', help_text='Descrição do Produto', max_length=200, verbose_name='Descrição')),
                ('price', models.FloatField(help_text='Preço do Produto', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do Produto', max_length=50, verbose_name='Nome')),
                ('description', models.TextField(default='', help_text='Descrição do Produto', max_length=200, verbose_name='Descrição')),
                ('price', models.FloatField(help_text='Preço do Produto', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
