# Generated by Django 2.0.8 on 2018-11-20 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomboniere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Quantidade de Produtos no Combo', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
    ]
