# Generated by Django 2.0.8 on 2018-11-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomboniere', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='quantity',
        ),
    ]
