# Generated by Django 2.0.8 on 2018-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomboniere', '0004_remove_combo_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(help_text='Produtos do Combo', to='bomboniere.Product', verbose_name='Produtos'),
        ),
    ]
