# Generated by Django 2.0.8 on 2018-11-20 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomboniere', '0005_combo_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantidade de Produtos no Combo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Combo', to='bomboniere.Combo')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='comboproductquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='bomboniere.Product'),
        ),
    ]
