# Generated by Django 2.0.8 on 2018-11-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=50)),
                ('available_ticket_number', models.IntegerField()),
                ('total_ticket_number', models.IntegerField()),
            ],
        ),
    ]
