# Generated by Django 2.0.8 on 2018-11-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
    ]
