# Generated by Django 2.0.8 on 2018-11-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_session_spectacle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='spectacle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', related_query_name='session', to='spectacle.Spectacle'),
        ),
    ]
