# Generated by Django 2.0.8 on 2018-11-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20181119_2224'),
        ('session', '0004_auto_20181119_2316'),
    ]

    operations = [
    ]
