# Generated by Django 2.0.8 on 2018-11-22 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20181122_0246'),
        ('session', '0006_session_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', related_query_name='sessions', to='room.Room'),
        ),
    ]
