# Generated by Django 2.0.8 on 2018-11-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', related_query_name='session', to='session.Session'),
        ),
    ]
