# Generated by Django 2.0.8 on 2018-11-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20181119_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
