# Generated by Django 2.0.8 on 2018-11-21 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0, help_text='Preço', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(help_text='Assento', max_length=50, null=True, verbose_name='Assento'),
        ),
    ]
