# Generated by Django 2.0.8 on 2018-11-21 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='rate',
            field=models.FloatField(default=0.1, help_text='Taxa', verbose_name='Taxa'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=0, help_text='Preço Total', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Total'),
        ),
    ]
