# Generated by Django 2.0.8 on 2018-11-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20181121_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='statusPayment',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Aguardando', help_text='Status do Pagamento', max_length=20, verbose_name='Status'),
        ),
    ]
